### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 3)

### ISSUE THREAD

**Issue by valery-shap** [rrwick/Trycycler#23]
Hello,

Thank you for the great new tool!
I have the problem with one cluster and decided to run 
`trycycler dotplot --cluster_dir trycycler/cluster_003`
but I have the error:
```
Traceback (most recent call last):
  File "/home/miniconda3/envs/trycycler/bin/trycycler", line 10, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/trycycler/lib/python3.9/site-packages/trycycler/__main__.py", line 45, in main
    dotplot(args)
  File "/home/miniconda3/envs/trycycler/lib/python3.9/site-packages/trycycler/dotplot.py", line 43, in dotplot
    image = create_dotplots(seq_names, seqs, args)
  File "/home/miniconda3/envs/trycycler/lib/python3.9/site-packages/trycycler/dotplot.py", line 90, in create_dotplots
    draw_labels(image, seq_names, start_positions, end_positions, text_gap, outline_width,
  File "/home/miniconda3/envs/trycycler/lib/python3.9/site-packages/trycycler/dotplot.py", line 173, in draw_labels
    font, text_width, text_height, font_size = \
ValueError: not enough values to unpack (expected 4, got 3)
```
How could I fix it?
version of Trycycler 0.5.1

Valery

**Comment by rrwick** [comment]
Hi Valery,

What you did makes sense to me: look for individual long reads that span the cassettes entirely and see how many cassette copies they indicate. It seems like cassette x3 is the answer, and that is also the most popular version in your cluster (10/21 contigs). So I'd remove all contigs that have any other cassette count and reconcile with just those 10 contigs.

The repetitive nature of the cassettes probably confused the assemblers, leading to misassemblies. However, one other possibility is that the number of cassettes is variable - i.e. sometimes the cassettes actually comes in 1, 2, 3 or 4 copies. That's a tougher situation because there isn't really a single answer, so you'd just have to pick one (preferably the most common, e.g. 3x) and run with it.

Ryan
