### ISSUE TITLE
Running trycylcer cluster under python3.7

### ISSUE THREAD

**Issue by AmyNjaaye** [rrwick/Trycycler#32]
Hi, I’m @AmyNjaaye and curently testing trycycler cluster. I encounter the following error at the Building distance matrix:

```
Traceback (most recent call last):
  File "/usr/bin/trycycler", line 11, in <module>
    load_entry_point('Trycycler==0.5.3', 'console_scripts', 'trycycler')()
  File "/usr/lib/python3/dist-packages/trycycler/__main__.py", line 41, in main
    cluster(args)
  File "/usr/lib/python3/dist-packages/trycycler/cluster.py", line 41, in cluster
    matrix = distance_matrix(seqs, seq_names, args.distance)
  File "/usr/lib/python3/dist-packages/trycycler/cluster.py", line 234, in distance_matrix
    mash_matrix = get_mash_dist_matrix(seq_names, seqs, distance, indent=False)
  File "/usr/lib/python3/dist-packages/trycycler/mash.py", line 28, in get_mash_dist_matrix
    pos_sketches, neg_sketches = make_mash_sketches(seq_names, seqs, temp_dir)
  File "/usr/lib/python3/dist-packages/trycycler/mash.py", line 69, in make_mash_sketches
    str(fasta_pos)], stderr=dev_null)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['mash', 'sketch', '-n', '-o', '/tmp/tmpgmibvfqh/A_contig_1_pos.msh', '/tmp/tmpgmibvfqh/A_contig_1_pos.fasta']' died with <Signals.SIGSEGV: 11>.
```
It seems to be related with the python version. 
I used the great datasets available on the wiki for testing. 
Any idea about that error ?
Thank you for your response. 

Aminata

**Comment by rrwick** [comment]
Hi Amy,

I don't think the Python version is the problem - 3.7 should be fine. It looks like something has gone wrong when Trycycler tried to run `mash sketch`, specifically sketching `contig_1` of your first assembly. Can you double check that mash works on your system if you run it outside Trycycler? E.g. Just run `mash sketch anything.fasta` and see if that works. If you get an error, then the problem is with mash and it might need to be reinstalled.

Ryan
